openapi: 3.0.3
info:
  title: Upvest Investment API
  version: 1.9.0
  description: Upvest Investment API.
  contact:
    name: Upvest API Support
    email: api@upvest.co
    url: https://docs.upvest.co
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
tags:
  - name: Access Tokens
    description: All authentication related paths.
  - name: Webhooks
    description: All webhook related paths.
  - name: Users
    description: All user related paths.
  - name: User Identifiers
    description: All user identifiers related paths.
  - name: User Checks
    description: All user checks related paths.
  - name: Accounts
    description: All accounts related paths
  - name: Account Groups
    description: All account groups related paths
  - name: Reference Accounts
    description: All reference account related paths
  - name: Mandates
    description: All direct debit mandates related paths
  - name: Payments
    description: All payments related paths
  - name: Cash Balances
    description: All cash balance related paths
  - name: Instruments
    description: All instrument related paths.
  - name: Orders
    description: All order related paths.
  - name: Executions
    description: All execution related paths.
  - name: Positions
    description: All positions related paths.
  - name: Treasury Reports
    description: All treasury reports related paths.
  - name: Reports
    description: All reports related paths.
  - name: Taxes
    description: All taxes related paths.
  - name: Transactions
    description: All transactions related paths.
  - name: Fees
    description: All fees related paths.
  - name: Portfolios
    description: All portfolios related paths.
  - name: Valuations
    description: All valuations related paths.
  - name: Liquidations
    description: All accounts liquidations related paths.
  - name: Returns
    description: All accounts returns related paths.
  - name: Virtual Cash Balances
    description: All virtual cash balances related paths
servers:
  - url: https://sandbox.upvest.co
    description: Sandbox environment
  - url: https://api.upvest.co
    description: Live environment
paths:
  /auth/token:
    post:
      operationId: issue_token
      summary: Get an access token for requested scopes
      description: >-
        Get an access token to use with the API with specified scopes.


        You should _always_ scope your access tokens. You get one for read-access and separate ones for updating, creating or deleting resources.
      tags:
        - Access Tokens
  /auth/verify_keys:
    get:
      operationId: get_jwks
      summary: Get signing keys
      description: Get list of signing keys used to verify webhooks
      tags:
        - Webhooks
      security:
        - oauth-client-credentials:
            - webhooks:read
            - webhooks:admin
  /webhooks:
    get:
      operationId: list_webhooks
      summary: List all webhooks
      description: List all webhooks
      tags:
        - Webhooks
      security:
        - oauth-client-credentials:
            - webhooks:read
            - webhooks:admin
    post:
      operationId: create_webhook
      summary: Create a webhook subscription
      description: Create a webhook subscription
      tags:
        - Webhooks
      security:
        - oauth-client-credentials:
            - webhooks:admin
  "/webhooks/{webhook_id}":
    get:
      operationId: retrieve_webhook
      summary: Retrieve a webhook subscription
      description: Retrieve a webhook subscription
      tags:
        - Webhooks
      security:
        - oauth-client-credentials:
            - webhooks:read
            - webhooks:admin
    delete:
      operationId: delete_webhook
      summary: Delete a webhook subscription
      description: Delete a webhook subscription
      tags:
        - Webhooks
      security:
        - oauth-client-credentials:
            - webhooks:admin
    patch:
      operationId: update_webhook
      summary: Update a webhook subscription
      description: Update a webhook subscription
      tags:
        - Webhooks
      security:
        - oauth-client-credentials:
            - webhooks:admin
  "/webhooks/{webhook_id}/test":
    post:
      operationId: test_webhook
      summary: Test a webhook
      description: Test a webhook
      tags:
        - Webhooks
      security:
        - oauth-client-credentials:
            - webhooks:admin
  /users:
    get:
      operationId: list_users
      summary: Get all users
      description: Returns the list of all users.
      tags:
        - Users
      security:
        - oauth-client-credentials:
            - users:read
            - users:admin
    post:
      operationId: create_user
      summary: Create a user
      description: Creates a user.
      tags:
        - Users
      security:
        - oauth-client-credentials:
            - users:admin
  "/users/{user_id}":
    get:
      operationId: retrieve_user
      summary: Get a user by ID
      description: Returns the user specified by ID.
      tags:
        - Users
      security:
        - oauth-client-credentials:
            - users:read
            - users:admin
    delete:
      operationId: offboard_user
      summary: Offboard a user
      description: Starts the user offboarding process in the background.
      tags:
        - Users
      security:
        - oauth-client-credentials:
            - users:admin
  "/users/{user_id}/data_change_requests":
    post:
      operationId: user_data_change
      summary: Change user data
      description: Requests a data change for a user specified by ID.
      tags:
        - Users
      security:
        - oauth-client-credentials:
            - users:admin
  "/users/{user_id}/checks":
    get:
      operationId: list_user_checks
      summary: Get checks for a user
      description: Lists all checks for a user specified by ID.
      tags:
        - Users
      x-doctave-tags:
        - User Checks
      security:
        - oauth-client-credentials:
            - checks:read
            - checks:admin
    post:
      operationId: create_user_check
      summary: Create a new check for a user
      description: Creates a new check for a user specified by ID.
      tags:
        - Users
      x-doctave-tags:
        - User Checks
      security:
        - oauth-client-credentials:
            - checks:admin
  "/users/{user_id}/checks/{check_id}":
    get:
      operationId: retrieve_user_check
      summary: Get a user check by ID
      description: Retrieves a check for a user specified by its ID.
      tags:
        - Users
      x-doctave-tags:
        - User Checks
      security:
        - oauth-client-credentials:
            - checks:read
            - checks:admin
  "/users/{user_id}/identifiers":
    get:
      operationId: list_user_identifiers
      summary: Get user identifiers
      description: Lists all existing identifiers of a user used for transaction reporting.
      tags:
        - Users
      x-doctave-tags:
        - User Identifiers
      security:
        - oauth-client-credentials:
            - users:read
            - users:admin
    post:
      operationId: create_identifier
      summary: Create a user identifier
      description: Creates a new identifier for a user that will be used for transaction reporting obligations. This identifier is required for user activation if the user's nationalities do not allow reporting using the CONCAT format. More information can be found in the [guides](https://docs.upvest.co/guides/users_and_accounts/identifiers_low_prio).
      tags:
        - Users
      x-doctave-tags:
        - User Identifiers
      security:
        - oauth-client-credentials:
            - users:admin
  "/users/{user_id}/identifiers/{identifier_id}":
    get:
      operationId: retrieve_identifier
      summary: Get a user identifier by ID
      description: Returns an existing identifier of a given user used for transaction reporting.
      tags:
        - Users
      x-doctave-tags:
        - User Identifiers
      security:
        - oauth-client-credentials:
            - users:read
            - users:admin
    patch:
      operationId: update_identifier
      summary: Update a user identifier by ID
      description: Updates an existing identifier of a given user used for transaction reporting.
      tags:
        - Users
      x-doctave-tags:
        - User Identifiers
      security:
        - oauth-client-credentials:
            - users:admin
  "/users/{user_id}/account_groups":
    get:
      operationId: list_user_account_groups
      summary: Get user account groups
      description: Lists the account groups of a user specified by ID.
      tags:
        - Users
      security:
        - oauth-client-credentials:
            - accounts:read
            - accounts:admin
  "/account_groups/{account_group_id}":
    get:
      operationId: retrieve_account_group
      summary: Get an account group by ID
      description: Returns the account group specified bu its ID.
      tags:
        - Accounts
      x-doctave-tags:
        - Account Groups
      security:
        - oauth-client-credentials:
            - accounts:read
            - accounts:admin
    delete:
      operationId: account_group_closure
      summary: Close an account group by ID
      description: Initiates the closure request for an account group specified by its ID.
      tags:
        - Accounts
      x-doctave-tags:
        - Account Groups
      security:
        - oauth-client-credentials:
            - accounts:admin
  "/account_groups/{account_group_id}/payments/cash_balance":
    get:
      operationId: retrieve_cash_balance
      summary: Retrieve an account group's cash balance
      description: Retrieve an account group's cash balance
      tags:
        - Cash Balances
      security:
        - oauth-client-credentials:
            - positions:read
  "/users/{user_id}/accounts":
    get:
      operationId: list_user_accounts
      summary: Get user accounts
      description: Lists the accounts of a user specified by ID.
      tags:
        - Users
      security:
        - oauth-client-credentials:
            - accounts:read
            - accounts:admin
  "/accounts/{account_id}":
    get:
      operationId: retrieve_account
      summary: Get a user account by ID
      description: Returns the user account specified by its ID.
      tags:
        - Accounts
      security:
        - oauth-client-credentials:
            - accounts:read
            - accounts:admin
    patch:
      operationId: update_account
      summary: Update user account
      description: Updates the user account specified by its ID.
      tags:
        - Accounts
      security:
        - oauth-client-credentials:
            - accounts:admin
    delete:
      operationId: account_closure
      summary: Close a user account by ID
      description: Initiates the closure request for an account specified by its ID.
      tags:
        - Accounts
      security:
        - oauth-client-credentials:
            - accounts:admin
  "/accounts/{account_id}/positions":
    get:
      operationId: list_positions
      summary: List positions
      description: List of account positions
      tags:
        - Positions
      security:
        - oauth-client-credentials:
            - positions:read
  "/accounts/{account_id}/positions/{instrument_id}":
    get:
      operationId: retrieve_position
      summary: Retrieve position
      description: Retrieve an account position
      tags:
        - Positions
      security:
        - oauth-client-credentials:
            - positions:read
  "/users/{user_id}/payments/reference_accounts":
    get:
      operationId: list_reference_accounts
      summary: Get reference accounts of a user
      description: Returns the list of reference accounts of a user specified by ID.
      tags:
        - Reference Accounts
      security:
        - oauth-client-credentials:
            - reference_accounts:admin
            - reference_accounts:read
  /payments/reference_accounts:
    post:
      operationId: create_reference_account
      summary: Create a reference account
      description: Creates a new reference account for a user specified by ID.
      tags:
        - Reference Accounts
      security:
        - oauth-client-credentials:
            - reference_accounts:admin
  "/payments/reference_accounts/{reference_account_id}":
    get:
      operationId: retrieve_reference_account
      summary: Get a reference account by ID
      description: Retrieves the reference account specified by its ID.
      tags:
        - Reference Accounts
      security:
        - oauth-client-credentials:
            - reference_accounts:admin
            - reference_accounts:read
    delete:
      operationId: delete_reference_account
      summary: Delete a reference account by ID
      description: Deletes the reference account specified by its ID.
      tags:
        - Reference Accounts
      security:
        - oauth-client-credentials:
            - reference_accounts:admin
  "/users/{user_id}/payments/mandates":
    get:
      operationId: list_mandates
      summary: List mandates
      description: List mandates
      tags:
        - Mandates
      security:
        - oauth-client-credentials:
            - mandates:admin
            - mandates:read
  /payments/mandates:
    post:
      operationId: create_mandate
      summary: Create a mandate
      description: Create a mandate
      tags:
        - Mandates
      security:
        - oauth-client-credentials:
            - mandates:admin
  "/payments/mandates/{mandate_id}":
    get:
      operationId: retrieve_mandate
      summary: Retrieve a direct debit mandate
      description: Retrieve a direct debit mandate
      tags:
        - Mandates
      security:
        - oauth-client-credentials:
            - mandates:admin
            - mandates:read
    delete:
      operationId: delete_mandate
      summary: Delete mandate
      description: Delete mandate
      tags:
        - Mandates
      security:
        - oauth-client-credentials:
            - mandates:admin
  "/account_groups/{account_group_id}/payments/direct_debits":
    get:
      operationId: list_direct_debits
      summary: List direct debits
      description: List direct debits
      tags:
        - Payments
      security:
        - oauth-client-credentials:
            - payments:admin
            - payments:read
  /payments/direct_debits:
    post:
      operationId: create_direct_debit
      summary: Trigger a direct debit
      description: Trigger a direct debit
      tags:
        - Payments
      security:
        - oauth-client-credentials:
            - payments:admin
  "/payments/direct_debits/{direct_debit_id}":
    get:
      operationId: retrieve_direct_debit
      summary: Retrieve a direct debit
      description: Retrieve a direct debit
      tags:
        - Payments
      security:
        - oauth-client-credentials:
            - payments:admin
            - payments:read
  /payments/withdrawals:
    post:
      operationId: create_cash_withdrawal
      summary: Trigger a withdrawal
      description: Trigger a withdrawal
      tags:
        - Payments
      security:
        - oauth-client-credentials:
            - payments:admin
  "/payments/withdrawals/{withdrawal_id}":
    get:
      operationId: retrieve_cash_withdrawal
      summary: Retrieve withdrawal
      description: Retrieve withdrawal
      tags:
        - Payments
      security:
        - oauth-client-credentials:
            - payments:admin
            - payments:read
    delete:
      operationId: cancel_cash_withdrawal
      summary: Cancel withdrawal by ID
      description: Cancels a withdrawal specified by its ID. It is only possible to cancel a withdrawal if it has the status `NEW`.
      tags:
        - Payments
      security:
        - oauth-client-credentials:
            - payments:admin
  "/account_groups/{account_group_id}/payments/withdrawals":
    get:
      operationId: list_cash_withdrawals
      summary: List withdrawals
      description: List withdrawals
      tags:
        - Payments
      security:
        - oauth-client-credentials:
            - payments:admin
            - payments:read
  /account_groups:
    get:
      operationId: list_account_groups
      summary: Get account groups
      description: Returns a list of all account groups.
      tags:
        - Accounts
      x-doctave-tags:
        - Account Groups
      security:
        - oauth-client-credentials:
            - accounts:read
            - accounts:admin
    post:
      operationId: create_account_group
      summary: Create an account group
      description: Creates an account group.
      tags:
        - Accounts
      x-doctave-tags:
        - Account Groups
      security:
        - oauth-client-credentials:
            - accounts:admin
  /accounts:
    get:
      operationId: list_accounts
      summary: Get accounts
      description: Returns a list of all accounts.
      tags:
        - Accounts
      security:
        - oauth-client-credentials:
            - accounts:read
            - accounts:admin
    post:
      operationId: create_account
      summary: Create an account
      description: Creates an account.
      tags:
        - Accounts
      security:
        - oauth-client-credentials:
            - accounts:admin
  "/accounts/{account_id}/orders":
    get:
      operationId: list_account_orders
      summary: Get orders for an account by ID
      description: Returns a list of all orders for the account specified by its ID.
      tags:
        - Orders
      security:
        - oauth-client-credentials:
            - orders:read
            - orders:admin
  /fees/collections:
    get:
      operationId: list_fee_collections
      summary: Get fee collections
      description: Returns a list of fee collections.
      tags:
        - Fees
      security:
        - oauth-client-credentials:
            - fees:read
            - fees:admin
    post:
      operationId: create_fee_collection
      summary: Create a fee collection
      description: Creates a fee collection for pre-calculated fee amounts.
      tags:
        - Fees
      security:
        - oauth-client-credentials:
            - fees:admin
  "/fees/collections/{fee_collection_id}":
    get:
      operationId: retrieve_fee_collection
      summary: Get a fee collection by ID
      description: Returns the fee collection specified by its ID.
      tags:
        - Fees
      security:
        - oauth-client-credentials:
            - fees:read
            - fees:admin
  /instruments:
    get:
      operationId: list_instruments
      summary: List instruments
      description: List instruments
      tags:
        - Instruments
      security:
        - oauth-client-credentials:
            - instruments:read
  "/instruments/{instrument_id}":
    get:
      operationId: retrieve_instrument
      summary: Retrieve instrument
      description: Retrieve instrument
      tags:
        - Instruments
      security:
        - oauth-client-credentials:
            - instruments:read
  /orders:
    post:
      operationId: place_order
      summary: Place an order
      description: Places a new order. After the creation request for the order is accepted, further processing takes place asynchronously.
      tags:
        - Orders
      security:
        - oauth-client-credentials:
            - orders:admin
  "/orders/{order_id}":
    get:
      operationId: retrieve_order
      summary: Get an order by ID
      description: Returns the order specified by its ID.
      tags:
        - Orders
      security:
        - oauth-client-credentials:
            - orders:read
            - orders:admin
    delete:
      operationId: cancel_order
      summary: Cancel an order by ID
      description: Cancels an order specified by its ID. It is possible to cancel an order of the `NEW` status. Once a cancellation has been accepted, the further processing steps take place asynchronously and depending on the respective order status.
      tags:
        - Orders
      security:
        - oauth-client-credentials:
            - orders:admin
  "/orders/{order_id}/executions/{execution_id}":
    get:
      operationId: retrieve_order_execution
      summary: Get an order execution by ID
      description: Returns the order execution specified by its ID.
      tags:
        - Orders
      security:
        - oauth-client-credentials:
            - orders:read
            - orders:admin
  "/users/{user_id}/reports":
    get:
      operationId: list_reports
      summary: List user reports
      description: List user reports
      tags:
        - Reports
      security:
        - oauth-client-credentials:
            - reports:read
  "/reports/{report_id}":
    get:
      operationId: retrieve_report
      summary: Retrieve a user report
      description: Retrieve a user report
      tags:
        - Reports
      security:
        - oauth-client-credentials:
            - reports:read
  "/users/{user_id}/tax_residencies":
    get:
      operationId: retrieve_tax_residencies
      summary: Retrieve tax residencies
      description: Retrieve tax residencies
      tags:
        - Taxes
      security:
        - oauth-client-credentials:
            - taxes:read
            - taxes:admin
    post:
      operationId: set_tax_residencies
      summary: Update tax residencies
      description: Update tax residencies
      tags:
        - Taxes
      security:
        - oauth-client-credentials:
            - taxes:admin
  /portfolios/allocations:
    get:
      operationId: list_portfolios_allocations
      summary: List portfolios allocations
      description: List portfolios allocations
      tags:
        - Portfolios
      security:
        - oauth-client-credentials:
            - portfolios:read
            - portfolios:admin
    post:
      operationId: create_portfolios_allocation
      summary: Create portfolios allocation
      description: Create portfolios allocation
      tags:
        - Portfolios
      security:
        - oauth-client-credentials:
            - portfolios:admin
  "/portfolios/allocations/{allocation_id}":
    get:
      operationId: retrieve_portfolios_allocation
      summary: Retrieve portfolios allocation
      description: Retrieve portfolios allocation
      tags:
        - Portfolios
      security:
        - oauth-client-credentials:
            - portfolios:read
            - portfolios:admin
    put:
      operationId: update_portfolios_allocation
      summary: Update portfolios allocation
      description: Update portfolios allocation
      tags:
        - Portfolios
      security:
        - oauth-client-credentials:
            - portfolios:admin
  /portfolios/configurations:
    get:
      operationId: list_portfolios_configurations
      summary: List portfolios configurations
      description: List portfolios configurations
      tags:
        - Portfolios
      security:
        - oauth-client-credentials:
            - portfolios:read
            - portfolios:admin
    post:
      operationId: create_portfolios_configuration
      summary: Create portfolios configuration
      description: Create portfolios configuration
      tags:
        - Portfolios
      security:
        - oauth-client-credentials:
            - portfolios:admin
  "/portfolios/configurations/{account_id}":
    get:
      operationId: retrieve_portfolios_configuration
      summary: Retrieve portfolios configuration
      description: Retrieve portfolios configuration
      tags:
        - Portfolios
      security:
        - oauth-client-credentials:
            - portfolios:read
            - portfolios:admin
    patch:
      operationId: update_portfolios_configuration
      summary: Update portfolios configuration
      description: Update portfolios configuration
      tags:
        - Portfolios
      security:
        - oauth-client-credentials:
            - portfolios:admin
  /portfolios/orders:
    get:
      operationId: list_portfolios_orders
      summary: List portfolios orders
      description: List portfolios orders
      tags:
        - Portfolios
      security:
        - oauth-client-credentials:
            - portfolios:read
            - portfolios:admin
    post:
      operationId: create_portfolios_order
      summary: Create portfolios order
      description: Create portfolios order
      tags:
        - Portfolios
      security:
        - oauth-client-credentials:
            - portfolios:admin
  "/portfolios/orders/{portfolio_order_id}":
    get:
      operationId: retrieve_portfolios_order
      summary: Retrieve portfolios order
      description: Retrieve portfolios order
      tags:
        - Portfolios
      security:
        - oauth-client-credentials:
            - portfolios:read
            - portfolios:admin
    delete:
      operationId: cancel_portfolios_order
      summary: Cancel portfolios order
      description: Cancel portfolios order
      tags:
        - Portfolios
      security:
        - oauth-client-credentials:
            - portfolios:admin
  /portfolios/rebalancings/executions:
    post:
      operationId: trigger_portfolio_rebalancing
      summary: Trigger portfolio rebalancing
      description: Trigger portfolio rebalancing
      tags:
        - Portfolios
      security:
        - oauth-client-credentials:
            - portfolios:admin
  "/portfolios/rebalancings/executions/{execution_id}":
    get:
      operationId: retrieve_portfolios_rebalancing_execution
      summary: Retrieve portfolios rebalancing execution
      description: Retrieve portfolios rebalancing execution
      tags:
        - Portfolios
      security:
        - oauth-client-credentials:
            - portfolios:read
            - portfolios:admin
  "/portfolios/rebalancings/executions/{execution_id}/orders":
    get:
      operationId: list_portfolio_rebalancing_execution_orders
      summary: List portfolio rebalancing execution orders
      description: List portfolio rebalancing execution orders
      tags:
        - Portfolios
      security:
        - oauth-client-credentials:
            - portfolios:read
            - portfolios:admin
  /portfolios/rebalancings/strategies:
    get:
      operationId: list_portfolios_rebalancing_strategies
      summary: List portfolios rebalancing strategies
      description: List portfolios rebalancing strategies
      tags:
        - Portfolios
      security:
        - oauth-client-credentials:
            - portfolios:read
            - portfolios:admin
    post:
      operationId: create_portfolios_rebalancing_strategy
      summary: Create portfolios rebalancing strategy
      description: Create portfolios rebalancing strategy
      tags:
        - Portfolios
      security:
        - oauth-client-credentials:
            - portfolios:admin
  "/portfolios/rebalancings/strategies/{strategy_id}":
    get:
      operationId: retrieve_portfolios_rebalancing_strategy
      summary: Retrieve portfolios rebalancing strategy
      description: Retrieve portfolios rebalancing strategy
      tags:
        - Portfolios
      security:
        - oauth-client-credentials:
            - portfolios:read
            - portfolios:admin
  "/portfolios/allocations/{allocation_id}/accounts":
    get:
      operationId: list_portfolios_allocation_accounts
      summary: List portfolios allocation accounts
      description: List portfolios allocation accounts
      tags:
        - Portfolios
      security:
        - oauth-client-credentials:
            - portfolios:read
            - portfolios:admin
  "/accounts/{account_id}/valuations/current":
    get:
      operationId: get_account_valuation
      summary: Get current valuation for an account
      description: Get current valuation for an account
      tags:
        - Valuations
      security:
        - oauth-client-credentials:
            - valuations:read
  "/accounts/{account_id}/valuations":
    get:
      operationId: list_account_valuation_history
      summary: List valuation history for an account
      description: List valuation history for an account
      tags:
        - Valuations
      security:
        - oauth-client-credentials:
            - valuations:read
  /transactions/cash:
    get:
      operationId: list_cash_transactions
      summary: List cash transactions
      description: List cash transactions
      tags:
        - Transactions
      security:
        - oauth-client-credentials:
            - transactions:read
  /transactions/securities:
    get:
      operationId: list_securities_transactions
      summary: List securities transactions
      description: List securities transactions
      tags:
        - Transactions
      security:
        - oauth-client-credentials:
            - transactions:read
  "/accounts/{account_id}/liquidations":
    get:
      operationId: list_accounts_liquidations
      summary: List accounts liquidations
      description: List accounts liquidations
      tags:
        - Liquidations
      security:
        - oauth-client-credentials:
            - account_liquidations:read
            - account_liquidations:admin
    post:
      operationId: create_account_liquidation
      summary: Create account liquidation request
      description: Create account liquidation request
      tags:
        - Liquidations
      security:
        - oauth-client-credentials:
            - account_liquidations:admin
  "/accounts/{account_id}/liquidations/{account_liquidation_id}":
    get:
      operationId: retrieve_account_liquidation
      summary: Retrieve account liquidation
      description: Retrieve account liquidation
      tags:
        - Liquidations
      security:
        - oauth-client-credentials:
            - account_liquidations:read
            - account_liquidations:admin
    delete:
      operationId: cancel_account_liquidation
      summary: Cancel account liquidation
      description: Cancel account liquidation
      tags:
        - Liquidations
      security:
        - oauth-client-credentials:
            - account_liquidations:admin
  "/accounts/{account_id}/returns":
    get:
      operationId: list_account_returns
      summary: List account returns
      description: List account returns
      tags:
        - Returns
      security:
        - oauth-client-credentials:
            - account_returns:read
  /virtual_cash_balances/increases:
    post:
      operationId: create_virtual_cash_increase
      summary: Trigger a virtual cash increase
      description: Trigger a virtual cash increase
      tags:
        - Virtual Cash Balances
      security:
        - oauth-client-credentials:
            - virtual_cash_balances:admin
  /virtual_cash_balances/decreases:
    post:
      operationId: create_virtual_cash_decrease
      summary: Trigger a virtual cash decrease
      description: Trigger a virtual cash decrease
      tags:
        - Virtual Cash Balances
      security:
        - oauth-client-credentials:
            - virtual_cash_balances:admin
  "/virtual_cash_balances/decreases/{virtual_cash_decrease_id}":
    delete:
      operationId: cancel_virtual_cash_decrease
      summary: Cancel virtual cash decrease by ID
      description: Cancels a virtual cash decrease specified by its ID. It is only possible to cancel a virtual cash decrease if it has the status `ISSUED` or `QUEUED`.
      tags:
        - Virtual Cash Balances
      security:
        - oauth-client-credentials:
            - virtual_cash_balances:admin
x-webhooks:
  Users events:
    post:
      operationId: user_event
      summary: Users events
      description: Users events
      tags:
        - Users
  User checks events:
    post:
      operationId: user_checks_event
      summary: User checks events
      description: User checks events
      tags:
        - Users
      x-doctave-tags:
        - User Checks
  Orders events:
    post:
      operationId: order_event
      summary: Orders events
      description: Orders events
      tags:
        - Orders
  Executions events:
    post:
      operationId: execution_event
      summary: Executions events
      description: Executions events
      tags:
        - Executions
      x-doctave-tags:
        - Orders
  Order Cancellations events:
    post:
      operationId: order_cancellation_event
      summary: Order Cancellations events
      description: Order Cancellations events
      tags:
        - Orders
      x-doctave-tags:
        - Orders
  Positions events:
    post:
      operationId: position_event
      summary: Positions events
      description: Positions events
      tags:
        - Positions
  Cash Balance events:
    post:
      operationId: cash_balance_event
      summary: Cash Balance events
      description: Cash Balance events
      tags:
        - Cash Balances
  Cash transactions events:
    post:
      operationId: cash_transaction_event
      summary: Cash transactions events
      description: Cash transactions events
      tags:
        - Transactions
  Security transactions events:
    post:
      operationId: security_transaction_event
      summary: Security transactions events
      description: Security transactions events
      tags:
        - Transactions
  Treasury reports events:
    post:
      operationId: treasury_report_event
      summary: Treasury reports events
      description: Treasury reports events
      tags:
        - Treasury Reports
  User reports events:
    post:
      operationId: report_event
      summary: User reports events
      description: User reports events
      tags:
        - Reports
  Account events:
    post:
      operationId: account_event
      summary: Account events
      description: Account events
      tags:
        - Accounts
  Account Group events:
    post:
      operationId: account_group_event
      summary: Account group events
      description: Account group events
      tags:
        - Account Groups
  Direct Debit events:
    post:
      operationId: direct_debit_event
      summary: Direct Debit events
      description: Direct Debit events
      tags:
        - Payments
  Withdrawals events:
    post:
      operationId: withdrawal_event
      summary: Withdrawals events
      description: Withdrawals events
      tags:
        - Payments
  Portfolio orders events:
    post:
      operationId: portfolio_order_event
      summary: Portfolios orders events
      description: Portfolios orders events
      tags:
        - Portfolios
  Portfolio allocations events:
    post:
      operationId: portfolio_allocation_event
      summary: Portfolios allocations events
      description: Portfolios allocations events
      tags:
        - Portfolios
  Account valuation events:
    post:
      operationId: account_valuation_event
      summary: Account valuation events
      description: Account valuation events
      tags:
        - Valuations
  Intraday account valuation events:
    post:
      operationId: intraday_account_valuation_event
      summary: Intraday account valuation events
      description: Intraday account valuation events
      tags:
        - Valuations
  Account liquidation events:
    post:
      operationId: account_liquidation_event
      summary: Account liquidation events
      description: Account liquidation events
      tags:
        - Liquidations
  Account returns events:
    post:
      operationId: account_returns_event
      summary: Account returns event
      description: Account returns event
      tags:
        - Returns
  Virtual cash increase events:
    post:
      operationId: virtual_cash_increase_event
      summary: Virtual cash increase events
      description: Virtual cash increase events
      tags:
        - Virtual Cash Balances
  Virtual cash decrease events:
    post:
      operationId: virtual_cash_decrease_event
      summary: Virtual cash decrease events
      description: Virtual cash decrease events
      tags:
        - Virtual Cash Balances
  Fee collection events:
    post:
      operationId: fee_collection_event
      summary: Fee collection events
      description: Fee collection events
      tags:
        - Fees
components:
  securitySchemes:
    oauth-client-credentials:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://sandbox.upvest.co/auth/token
          scopes:
            accounts:read: Read accounts and account groups
            accounts:admin: Create/update/delete accounts and account groups
            webhooks:admin: Create/update/delete webhooks
            webhooks:read: Read webhooks
            orders:admin: Create/update/delete orders
            orders:read: Read orders
            users:admin: Create/update/delete users
            users:read: Read users
            checks:admin: Create checks
            checks:read: Read checks
            positions:read: Read positions
            reference_accounts:admin: Create/update/delete reference accounts
            reference_accounts:read: Read reference accounts
            mandates:admin: Create/update/delete mandates
            mandates:read: Read mandates
            payments:admin: Payins and withdrawal operations
            payments:read: Payins and withdrawal read operations
            topups:admin: Topups operations
            topups:read: Topups read operations
            credit_fundings:read: Credit Fundings read operations
            reports:read: Read reports
            taxes:read: Read tax residencies
            taxes:admin: Modify tax residencies
            transactions:read: Read cash and securities transactions
            instruments:read: Read instruments
            fees:admin: Create and read fee operations
            fees:read: Read fee operations
            portfolios:read: Read portfolios
            portfolios:admin: Modify portfolios
            valuations:read: Read valuations
            account_liquidations:read: Read accounts liquidations
            account_liquidations:admin: Trigger/read/cancel accounts liquidations
            account_returns:read: Read accounts returns
            virtual_cash_balances:admin: Virtual cash balances