// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/upvest-dev-sample-sdk/pkg/models/shared"
	"github.com/speakeasy-sdks/upvest-dev-sample-sdk/pkg/utils"
	"net/http"
	"time"
)

type CreateDirectDebitSecurity struct {
	OauthClientCredentials string `security:"scheme,type=oauth2,name=Authorization"`
}

func (o *CreateDirectDebitSecurity) GetOauthClientCredentials() string {
	if o == nil {
		return ""
	}
	return o.OauthClientCredentials
}

type CreateDirectDebitPaymentsDirectDebitCreateRequest struct {
	// Account group unique identifier.
	AccountGroupID string `json:"account_group_id"`
	CashAmount     string `json:"cash_amount"`
	// Direct Debit Mandate unique identifier.
	MandateID string `json:"mandate_id"`
	// Payment reference the end user will see in their bank statement for the corresponding direct debit booking (“Verwendungszweck”)
	RemittanceInformation *string `json:"remittance_information,omitempty"`
	// User unique identifier.
	UserID string `json:"user_id"`
}

func (o *CreateDirectDebitPaymentsDirectDebitCreateRequest) GetAccountGroupID() string {
	if o == nil {
		return ""
	}
	return o.AccountGroupID
}

func (o *CreateDirectDebitPaymentsDirectDebitCreateRequest) GetCashAmount() string {
	if o == nil {
		return ""
	}
	return o.CashAmount
}

func (o *CreateDirectDebitPaymentsDirectDebitCreateRequest) GetMandateID() string {
	if o == nil {
		return ""
	}
	return o.MandateID
}

func (o *CreateDirectDebitPaymentsDirectDebitCreateRequest) GetRemittanceInformation() *string {
	if o == nil {
		return nil
	}
	return o.RemittanceInformation
}

func (o *CreateDirectDebitPaymentsDirectDebitCreateRequest) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}

type CreateDirectDebitRequest struct {
	RequestBody *CreateDirectDebitPaymentsDirectDebitCreateRequest `request:"mediaType=application/json"`
	// A UUID to be used as an idempotency key.  This prevents a duplicate request from being replayed.
	// https://docs.upvest.co/concepts/api_concepts/idempotency
	//
	IdempotencyKey string `header:"style=simple,explode=false,name=idempotency-key"`
	// https://tools.ietf.org/id/draft-ietf-httpbis-message-signatures-01.html#name-the-signature-http-header
	Signature string `header:"style=simple,explode=false,name=signature"`
	// https://tools.ietf.org/id/draft-ietf-httpbis-message-signatures-01.html#name-the-signature-input-http-he
	SignatureInput string `header:"style=simple,explode=false,name=signature-input"`
	// Upvest API version (Note: Do not include quotation marks)
	UpvestAPIVersion *shared.APIVersion `default:"1" header:"style=simple,explode=false,name=upvest-api-version"`
	// Tenant Client ID
	UpvestClientID string `header:"style=simple,explode=false,name=upvest-client-id"`
}

func (c CreateDirectDebitRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateDirectDebitRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CreateDirectDebitRequest) GetRequestBody() *CreateDirectDebitPaymentsDirectDebitCreateRequest {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *CreateDirectDebitRequest) GetIdempotencyKey() string {
	if o == nil {
		return ""
	}
	return o.IdempotencyKey
}

func (o *CreateDirectDebitRequest) GetSignature() string {
	if o == nil {
		return ""
	}
	return o.Signature
}

func (o *CreateDirectDebitRequest) GetSignatureInput() string {
	if o == nil {
		return ""
	}
	return o.SignatureInput
}

func (o *CreateDirectDebitRequest) GetUpvestAPIVersion() *shared.APIVersion {
	if o == nil {
		return nil
	}
	return o.UpvestAPIVersion
}

func (o *CreateDirectDebitRequest) GetUpvestClientID() string {
	if o == nil {
		return ""
	}
	return o.UpvestClientID
}

// CreateDirectDebitCurrency - Alphabetic three-letter [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code.
// * EUR - Euro
type CreateDirectDebitCurrency string

const (
	CreateDirectDebitCurrencyEur CreateDirectDebitCurrency = "EUR"
)

func (e CreateDirectDebitCurrency) ToPointer() *CreateDirectDebitCurrency {
	return &e
}

func (e *CreateDirectDebitCurrency) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EUR":
		*e = CreateDirectDebitCurrency(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateDirectDebitCurrency: %v", v)
	}
}

// CreateDirectDebitStatus - Status of the direct debit
// * NEW - Direct debit is created but not started processing.
// * PROCESSING - Direct debit is in processing.
// * CONFIRMED - Direct debit was successfully processed.
// * CANCELLED - Direct debit was cancelled.
type CreateDirectDebitStatus string

const (
	CreateDirectDebitStatusNew        CreateDirectDebitStatus = "NEW"
	CreateDirectDebitStatusProcessing CreateDirectDebitStatus = "PROCESSING"
	CreateDirectDebitStatusConfirmed  CreateDirectDebitStatus = "CONFIRMED"
	CreateDirectDebitStatusCancelled  CreateDirectDebitStatus = "CANCELLED"
)

func (e CreateDirectDebitStatus) ToPointer() *CreateDirectDebitStatus {
	return &e
}

func (e *CreateDirectDebitStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NEW":
		fallthrough
	case "PROCESSING":
		fallthrough
	case "CONFIRMED":
		fallthrough
	case "CANCELLED":
		*e = CreateDirectDebitStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateDirectDebitStatus: %v", v)
	}
}

// CreateDirectDebitResponseBody - Direct debit
type CreateDirectDebitResponseBody struct {
	// Account group unique identifier.
	AccountGroupID string `json:"account_group_id"`
	CashAmount     string `json:"cash_amount"`
	// Date and time when the resource was created. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
	CreatedAt time.Time `json:"created_at"`
	// Alphabetic three-letter [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code.
	// * EUR - Euro
	Currency *CreateDirectDebitCurrency `default:"EUR" json:"currency"`
	// Direct debit funding request unique identifier
	ID string `json:"id"`
	// Direct Debit Mandate unique identifier.
	MandateID string `json:"mandate_id"`
	// Payment reference the end user will see in their bank statement for the corresponding direct debit booking (“Verwendungszweck”)
	RemittanceInformation *string `json:"remittance_information,omitempty"`
	// Status of the direct debit
	// * NEW - Direct debit is created but not started processing.
	// * PROCESSING - Direct debit is in processing.
	// * CONFIRMED - Direct debit was successfully processed.
	// * CANCELLED - Direct debit was cancelled.
	Status *CreateDirectDebitStatus `json:"status,omitempty"`
	// User unique identifier.
	UserID string `json:"user_id"`
}

func (c CreateDirectDebitResponseBody) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateDirectDebitResponseBody) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CreateDirectDebitResponseBody) GetAccountGroupID() string {
	if o == nil {
		return ""
	}
	return o.AccountGroupID
}

func (o *CreateDirectDebitResponseBody) GetCashAmount() string {
	if o == nil {
		return ""
	}
	return o.CashAmount
}

func (o *CreateDirectDebitResponseBody) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *CreateDirectDebitResponseBody) GetCurrency() *CreateDirectDebitCurrency {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *CreateDirectDebitResponseBody) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateDirectDebitResponseBody) GetMandateID() string {
	if o == nil {
		return ""
	}
	return o.MandateID
}

func (o *CreateDirectDebitResponseBody) GetRemittanceInformation() *string {
	if o == nil {
		return nil
	}
	return o.RemittanceInformation
}

func (o *CreateDirectDebitResponseBody) GetStatus() *CreateDirectDebitStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *CreateDirectDebitResponseBody) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}

type CreateDirectDebitResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Direct debit
	Object *CreateDirectDebitResponseBody
}

func (o *CreateDirectDebitResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateDirectDebitResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *CreateDirectDebitResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateDirectDebitResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateDirectDebitResponse) GetObject() *CreateDirectDebitResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}
