// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/upvest-dev-sample-sdk/pkg/models/shared"
	"github.com/speakeasy-sdks/upvest-dev-sample-sdk/pkg/types"
	"github.com/speakeasy-sdks/upvest-dev-sample-sdk/pkg/utils"
	"net/http"
	"time"
)

// Currency - Alphabetic three-letter [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code.
// * EUR - Euro
type Currency string

const (
	CurrencyEur Currency = "EUR"
)

func (e Currency) ToPointer() *Currency {
	return &e
}

func (e *Currency) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EUR":
		*e = Currency(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Currency: %v", v)
	}
}

// CreateFeeCollectionType - Type of the fee collection
// * SERVICE_FEE - Service fee intake in a pre-defined cadence (e.g. monthly)
// * SERVICE_FEE_LIQUIDATION - Service fee intake as a result of a Portfolio liquidation
type CreateFeeCollectionType string

const (
	CreateFeeCollectionTypeServiceFee            CreateFeeCollectionType = "SERVICE_FEE"
	CreateFeeCollectionTypeServiceFeeLiquidation CreateFeeCollectionType = "SERVICE_FEE_LIQUIDATION"
)

func (e CreateFeeCollectionType) ToPointer() *CreateFeeCollectionType {
	return &e
}

func (e *CreateFeeCollectionType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "SERVICE_FEE":
		fallthrough
	case "SERVICE_FEE_LIQUIDATION":
		*e = CreateFeeCollectionType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateFeeCollectionType: %v", v)
	}
}

type CreateFeeCollectionFeeCollectionCreateRequest struct {
	// Account unique identifier.
	AccountID        string `json:"account_id"`
	CollectionAmount string `json:"collection_amount"`
	// Alphabetic three-letter [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code.
	// * EUR - Euro
	Currency *Currency `default:"EUR" json:"currency"`
	// End date of the fee collection period in YYYY-MM-DD format. [RFC 3339, section 5.6](https://json-schema.org/draft/2020-12/json-schema-validation.html#RFC3339) RFC 3339
	PeriodEnd types.Date `json:"period_end"`
	// Start date of the fee collection period in YYYY-MM-DD format. [RFC 3339, section 5.6](https://json-schema.org/draft/2020-12/json-schema-validation.html#RFC3339) RFC 3339
	PeriodStart types.Date `json:"period_start"`
	// Type of the fee collection
	// * SERVICE_FEE - Service fee intake in a pre-defined cadence (e.g. monthly)
	// * SERVICE_FEE_LIQUIDATION - Service fee intake as a result of a Portfolio liquidation
	Type CreateFeeCollectionType `json:"type"`
}

func (c CreateFeeCollectionFeeCollectionCreateRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateFeeCollectionFeeCollectionCreateRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CreateFeeCollectionFeeCollectionCreateRequest) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

func (o *CreateFeeCollectionFeeCollectionCreateRequest) GetCollectionAmount() string {
	if o == nil {
		return ""
	}
	return o.CollectionAmount
}

func (o *CreateFeeCollectionFeeCollectionCreateRequest) GetCurrency() *Currency {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *CreateFeeCollectionFeeCollectionCreateRequest) GetPeriodEnd() types.Date {
	if o == nil {
		return types.Date{}
	}
	return o.PeriodEnd
}

func (o *CreateFeeCollectionFeeCollectionCreateRequest) GetPeriodStart() types.Date {
	if o == nil {
		return types.Date{}
	}
	return o.PeriodStart
}

func (o *CreateFeeCollectionFeeCollectionCreateRequest) GetType() CreateFeeCollectionType {
	if o == nil {
		return CreateFeeCollectionType("")
	}
	return o.Type
}

type CreateFeeCollectionRequest struct {
	RequestBody *CreateFeeCollectionFeeCollectionCreateRequest `request:"mediaType=application/json"`
	// A UUID to be used as an idempotency key.  This prevents a duplicate request from being replayed.
	// https://docs.upvest.co/concepts/api_concepts/idempotency
	//
	IdempotencyKey string `header:"style=simple,explode=false,name=idempotency-key"`
	// https://tools.ietf.org/id/draft-ietf-httpbis-message-signatures-01.html#name-the-signature-http-header
	Signature string `header:"style=simple,explode=false,name=signature"`
	// https://tools.ietf.org/id/draft-ietf-httpbis-message-signatures-01.html#name-the-signature-input-http-he
	SignatureInput string `header:"style=simple,explode=false,name=signature-input"`
	// Upvest API version (Note: Do not include quotation marks)
	UpvestAPIVersion *shared.APIVersion `default:"1" header:"style=simple,explode=false,name=upvest-api-version"`
	// Tenant Client ID
	UpvestClientID string `header:"style=simple,explode=false,name=upvest-client-id"`
}

func (c CreateFeeCollectionRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateFeeCollectionRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CreateFeeCollectionRequest) GetRequestBody() *CreateFeeCollectionFeeCollectionCreateRequest {
	if o == nil {
		return nil
	}
	return o.RequestBody
}

func (o *CreateFeeCollectionRequest) GetIdempotencyKey() string {
	if o == nil {
		return ""
	}
	return o.IdempotencyKey
}

func (o *CreateFeeCollectionRequest) GetSignature() string {
	if o == nil {
		return ""
	}
	return o.Signature
}

func (o *CreateFeeCollectionRequest) GetSignatureInput() string {
	if o == nil {
		return ""
	}
	return o.SignatureInput
}

func (o *CreateFeeCollectionRequest) GetUpvestAPIVersion() *shared.APIVersion {
	if o == nil {
		return nil
	}
	return o.UpvestAPIVersion
}

func (o *CreateFeeCollectionRequest) GetUpvestClientID() string {
	if o == nil {
		return ""
	}
	return o.UpvestClientID
}

// CreateFeeCollectionCurrency - Alphabetic three-letter [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code.
// * EUR - Euro
type CreateFeeCollectionCurrency string

const (
	CreateFeeCollectionCurrencyEur CreateFeeCollectionCurrency = "EUR"
)

func (e CreateFeeCollectionCurrency) ToPointer() *CreateFeeCollectionCurrency {
	return &e
}

func (e *CreateFeeCollectionCurrency) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EUR":
		*e = CreateFeeCollectionCurrency(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateFeeCollectionCurrency: %v", v)
	}
}

type ProcessedAmount struct {
	CashBalance *string `json:"cash_balance,omitempty"`
	SellToCover *string `json:"sell_to_cover,omitempty"`
}

func (o *ProcessedAmount) GetCashBalance() *string {
	if o == nil {
		return nil
	}
	return o.CashBalance
}

func (o *ProcessedAmount) GetSellToCover() *string {
	if o == nil {
		return nil
	}
	return o.SellToCover
}

// CreateFeeCollectionStatus - Status of the fee collection
// * PROCESSING - Fee collection is in progress.
// * FINALISED - Fees have been collected from the account and the funds has been transferred to the client.
// * CANCELLED - Fee collection has been cancelled.
type CreateFeeCollectionStatus string

const (
	CreateFeeCollectionStatusProcessing CreateFeeCollectionStatus = "PROCESSING"
	CreateFeeCollectionStatusFinalised  CreateFeeCollectionStatus = "FINALISED"
	CreateFeeCollectionStatusCancelled  CreateFeeCollectionStatus = "CANCELLED"
)

func (e CreateFeeCollectionStatus) ToPointer() *CreateFeeCollectionStatus {
	return &e
}

func (e *CreateFeeCollectionStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "PROCESSING":
		fallthrough
	case "FINALISED":
		fallthrough
	case "CANCELLED":
		*e = CreateFeeCollectionStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateFeeCollectionStatus: %v", v)
	}
}

// CreateFeeCollectionFeesType - Type of the fee collection
// * SERVICE_FEE - Service fee intake in a pre-defined cadence (e.g. monthly)
// * SERVICE_FEE_LIQUIDATION - Service fee intake as a result of a Portfolio liquidation
type CreateFeeCollectionFeesType string

const (
	CreateFeeCollectionFeesTypeServiceFee            CreateFeeCollectionFeesType = "SERVICE_FEE"
	CreateFeeCollectionFeesTypeServiceFeeLiquidation CreateFeeCollectionFeesType = "SERVICE_FEE_LIQUIDATION"
)

func (e CreateFeeCollectionFeesType) ToPointer() *CreateFeeCollectionFeesType {
	return &e
}

func (e *CreateFeeCollectionFeesType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "SERVICE_FEE":
		fallthrough
	case "SERVICE_FEE_LIQUIDATION":
		*e = CreateFeeCollectionFeesType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for CreateFeeCollectionFeesType: %v", v)
	}
}

// CreateFeeCollectionFeeCollection - Fee collection created.
type CreateFeeCollectionFeeCollection struct {
	// Account group unique identifier.
	AccountGroupID string `json:"account_group_id"`
	// Account unique identifier.
	AccountID        string `json:"account_id"`
	CollectionAmount string `json:"collection_amount"`
	// Date and time when the resource was created. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
	CreatedAt time.Time `json:"created_at"`
	// Alphabetic three-letter [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code.
	// * EUR - Euro
	Currency *CreateFeeCollectionCurrency `default:"EUR" json:"currency"`
	// Fee collection unique identifier.
	ID string `json:"id"`
	// End date of the fee collection period in YYYY-MM-DD format. [RFC 3339, section 5.6](https://json-schema.org/draft/2020-12/json-schema-validation.html#RFC3339) RFC 3339
	PeriodEnd types.Date `json:"period_end"`
	// Start date of the fee collection period in YYYY-MM-DD format. [RFC 3339, section 5.6](https://json-schema.org/draft/2020-12/json-schema-validation.html#RFC3339) RFC 3339
	PeriodStart     types.Date      `json:"period_start"`
	ProcessedAmount ProcessedAmount `json:"processed_amount"`
	// Status of the fee collection
	// * PROCESSING - Fee collection is in progress.
	// * FINALISED - Fees have been collected from the account and the funds has been transferred to the client.
	// * CANCELLED - Fee collection has been cancelled.
	Status CreateFeeCollectionStatus `json:"status"`
	// Type of the fee collection
	// * SERVICE_FEE - Service fee intake in a pre-defined cadence (e.g. monthly)
	// * SERVICE_FEE_LIQUIDATION - Service fee intake as a result of a Portfolio liquidation
	Type CreateFeeCollectionFeesType `json:"type"`
	// Date and time when the resource was last updated. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
	UpdatedAt time.Time `json:"updated_at"`
}

func (c CreateFeeCollectionFeeCollection) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateFeeCollectionFeeCollection) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *CreateFeeCollectionFeeCollection) GetAccountGroupID() string {
	if o == nil {
		return ""
	}
	return o.AccountGroupID
}

func (o *CreateFeeCollectionFeeCollection) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

func (o *CreateFeeCollectionFeeCollection) GetCollectionAmount() string {
	if o == nil {
		return ""
	}
	return o.CollectionAmount
}

func (o *CreateFeeCollectionFeeCollection) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *CreateFeeCollectionFeeCollection) GetCurrency() *CreateFeeCollectionCurrency {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *CreateFeeCollectionFeeCollection) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *CreateFeeCollectionFeeCollection) GetPeriodEnd() types.Date {
	if o == nil {
		return types.Date{}
	}
	return o.PeriodEnd
}

func (o *CreateFeeCollectionFeeCollection) GetPeriodStart() types.Date {
	if o == nil {
		return types.Date{}
	}
	return o.PeriodStart
}

func (o *CreateFeeCollectionFeeCollection) GetProcessedAmount() ProcessedAmount {
	if o == nil {
		return ProcessedAmount{}
	}
	return o.ProcessedAmount
}

func (o *CreateFeeCollectionFeeCollection) GetStatus() CreateFeeCollectionStatus {
	if o == nil {
		return CreateFeeCollectionStatus("")
	}
	return o.Status
}

func (o *CreateFeeCollectionFeeCollection) GetType() CreateFeeCollectionFeesType {
	if o == nil {
		return CreateFeeCollectionFeesType("")
	}
	return o.Type
}

func (o *CreateFeeCollectionFeeCollection) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

type CreateFeeCollectionResponse struct {
	// Fee collection created.
	TwoHundredApplicationJSONFeeCollection *CreateFeeCollectionFeeCollection
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *CreateFeeCollectionResponse) GetTwoHundredApplicationJSONFeeCollection() *CreateFeeCollectionFeeCollection {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONFeeCollection
}

func (o *CreateFeeCollectionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateFeeCollectionResponse) GetHeaders() map[string][]string {
	if o == nil {
		return map[string][]string{}
	}
	return o.Headers
}

func (o *CreateFeeCollectionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateFeeCollectionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
