// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/upvest-dev-sample-sdk/pkg/models/shared"
	"github.com/speakeasy-sdks/upvest-dev-sample-sdk/pkg/utils"
	"net/http"
	"time"
)

// PriceQuality - Defines the quality of the price used in the valuation.
type PriceQuality string

const (
	PriceQualityEod PriceQuality = "EOD"
)

func (e PriceQuality) ToPointer() *PriceQuality {
	return &e
}

func (e *PriceQuality) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EOD":
		*e = PriceQuality(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PriceQuality: %v", v)
	}
}

type GetAccountValuationRequest struct {
	AccountID string `pathParam:"style=simple,explode=false,name=account_id"`
	// Defines the quality of the price used in the valuation.
	PriceQuality PriceQuality `queryParam:"style=form,explode=true,name=price_quality"`
	// https://tools.ietf.org/id/draft-ietf-httpbis-message-signatures-01.html#name-the-signature-http-header
	Signature string `header:"style=simple,explode=false,name=signature"`
	// https://tools.ietf.org/id/draft-ietf-httpbis-message-signatures-01.html#name-the-signature-input-http-he
	SignatureInput string `header:"style=simple,explode=false,name=signature-input"`
	// Upvest API version (Note: Do not include quotation marks)
	UpvestAPIVersion *shared.APIVersion `default:"1" header:"style=simple,explode=false,name=upvest-api-version"`
	// Tenant Client ID
	UpvestClientID string `header:"style=simple,explode=false,name=upvest-client-id"`
}

func (g GetAccountValuationRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAccountValuationRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetAccountValuationRequest) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

func (o *GetAccountValuationRequest) GetPriceQuality() PriceQuality {
	if o == nil {
		return PriceQuality("")
	}
	return o.PriceQuality
}

func (o *GetAccountValuationRequest) GetSignature() string {
	if o == nil {
		return ""
	}
	return o.Signature
}

func (o *GetAccountValuationRequest) GetSignatureInput() string {
	if o == nil {
		return ""
	}
	return o.SignatureInput
}

func (o *GetAccountValuationRequest) GetUpvestAPIVersion() *shared.APIVersion {
	if o == nil {
		return nil
	}
	return o.UpvestAPIVersion
}

func (o *GetAccountValuationRequest) GetUpvestClientID() string {
	if o == nil {
		return ""
	}
	return o.UpvestClientID
}

// GetAccountValuationPriceQuality - Price quality used for the calculation of the account valuation.
// * EOD - end of day price
type GetAccountValuationPriceQuality string

const (
	GetAccountValuationPriceQualityEod GetAccountValuationPriceQuality = "EOD"
)

func (e GetAccountValuationPriceQuality) ToPointer() *GetAccountValuationPriceQuality {
	return &e
}

func (e *GetAccountValuationPriceQuality) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EOD":
		*e = GetAccountValuationPriceQuality(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetAccountValuationPriceQuality: %v", v)
	}
}

// GetAccountValuationInstrument - Entity representing the financial instrument.
type GetAccountValuationInstrument struct {
	// International securities identification number defined by [ISO 6166](https://en.wikipedia.org/wiki/International_Securities_Identification_Number).
	Isin *string `json:"isin,omitempty"`
	// String representing the instrument internal identifier.
	UUID string `json:"uuid"`
}

func (o *GetAccountValuationInstrument) GetIsin() *string {
	if o == nil {
		return nil
	}
	return o.Isin
}

func (o *GetAccountValuationInstrument) GetUUID() string {
	if o == nil {
		return ""
	}
	return o.UUID
}

// GetAccountValuationValuationsCurrency - Alphabetic three-letter [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code.
// * EUR - Euro
type GetAccountValuationValuationsCurrency string

const (
	GetAccountValuationValuationsCurrencyEur GetAccountValuationValuationsCurrency = "EUR"
)

func (e GetAccountValuationValuationsCurrency) ToPointer() *GetAccountValuationValuationsCurrency {
	return &e
}

func (e *GetAccountValuationValuationsCurrency) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EUR":
		*e = GetAccountValuationValuationsCurrency(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetAccountValuationValuationsCurrency: %v", v)
	}
}

// SecurityPositionValue - Entity representing the monetary value by amount and currency, and the time of the price used.
type SecurityPositionValue struct {
	Amount string `json:"amount"`
	// Alphabetic three-letter [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code.
	// * EUR - Euro
	Currency *GetAccountValuationValuationsCurrency `default:"EUR" json:"currency"`
	// The date and time of the price used for the calculation. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
	PriceTime time.Time `json:"price_time"`
}

func (s SecurityPositionValue) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(s, "", false)
}

func (s *SecurityPositionValue) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &s, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *SecurityPositionValue) GetAmount() string {
	if o == nil {
		return ""
	}
	return o.Amount
}

func (o *SecurityPositionValue) GetCurrency() *GetAccountValuationValuationsCurrency {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *SecurityPositionValue) GetPriceTime() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.PriceTime
}

type AccountValuationSecurityPosition struct {
	// Entity representing the financial instrument.
	Instrument GetAccountValuationInstrument `json:"instrument"`
	Quantity   string                        `json:"quantity"`
	Value      *SecurityPositionValue        `json:"value"`
	Weight     *string                       `json:"weight"`
}

func (o *AccountValuationSecurityPosition) GetInstrument() GetAccountValuationInstrument {
	if o == nil {
		return GetAccountValuationInstrument{}
	}
	return o.Instrument
}

func (o *AccountValuationSecurityPosition) GetQuantity() string {
	if o == nil {
		return ""
	}
	return o.Quantity
}

func (o *AccountValuationSecurityPosition) GetValue() *SecurityPositionValue {
	if o == nil {
		return nil
	}
	return o.Value
}

func (o *AccountValuationSecurityPosition) GetWeight() *string {
	if o == nil {
		return nil
	}
	return o.Weight
}

// GetAccountValuationCurrency - Alphabetic three-letter [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code.
// * EUR - Euro
type GetAccountValuationCurrency string

const (
	GetAccountValuationCurrencyEur GetAccountValuationCurrency = "EUR"
)

func (e GetAccountValuationCurrency) ToPointer() *GetAccountValuationCurrency {
	return &e
}

func (e *GetAccountValuationCurrency) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EUR":
		*e = GetAccountValuationCurrency(v)
		return nil
	default:
		return fmt.Errorf("invalid value for GetAccountValuationCurrency: %v", v)
	}
}

// TotalSecurityValue - Entity representing the monetary value by amount and currency.
type TotalSecurityValue struct {
	Amount string `json:"amount"`
	// Alphabetic three-letter [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code.
	// * EUR - Euro
	Currency *GetAccountValuationCurrency `default:"EUR" json:"currency"`
}

func (t TotalSecurityValue) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(t, "", false)
}

func (t *TotalSecurityValue) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &t, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *TotalSecurityValue) GetAmount() string {
	if o == nil {
		return ""
	}
	return o.Amount
}

func (o *TotalSecurityValue) GetCurrency() *GetAccountValuationCurrency {
	if o == nil {
		return nil
	}
	return o.Currency
}

// GetAccountValuationAccountValuation - Valuations
type GetAccountValuationAccountValuation struct {
	// Account unique identifier.
	AccountID string `json:"account_id"`
	// Date and time when the resource was created. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
	CreatedAt time.Time `json:"created_at"`
	// Account valuation unique identifier.
	ID string `json:"id"`
	// Price quality used for the calculation of the account valuation.
	// * EOD - end of day price
	PriceQuality *GetAccountValuationPriceQuality `default:"EOD" json:"price_quality"`
	// Positions associated with this account valuation.
	SecurityPositions []AccountValuationSecurityPosition `json:"security_positions,omitempty"`
	// Entity representing the monetary value by amount and currency.
	TotalSecurityValue TotalSecurityValue `json:"total_security_value"`
	// Date and time when the resource was last updated. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
	UpdatedAt time.Time `json:"updated_at"`
	// Date and time as of which the value was calculated. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
	ValuationTime time.Time `json:"valuation_time"`
}

func (g GetAccountValuationAccountValuation) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetAccountValuationAccountValuation) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *GetAccountValuationAccountValuation) GetAccountID() string {
	if o == nil {
		return ""
	}
	return o.AccountID
}

func (o *GetAccountValuationAccountValuation) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *GetAccountValuationAccountValuation) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetAccountValuationAccountValuation) GetPriceQuality() *GetAccountValuationPriceQuality {
	if o == nil {
		return nil
	}
	return o.PriceQuality
}

func (o *GetAccountValuationAccountValuation) GetSecurityPositions() []AccountValuationSecurityPosition {
	if o == nil {
		return nil
	}
	return o.SecurityPositions
}

func (o *GetAccountValuationAccountValuation) GetTotalSecurityValue() TotalSecurityValue {
	if o == nil {
		return TotalSecurityValue{}
	}
	return o.TotalSecurityValue
}

func (o *GetAccountValuationAccountValuation) GetUpdatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.UpdatedAt
}

func (o *GetAccountValuationAccountValuation) GetValuationTime() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.ValuationTime
}

type GetAccountValuationResponse struct {
	// Valuations
	TwoHundredApplicationJSONAccountValuation *GetAccountValuationAccountValuation
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetAccountValuationResponse) GetTwoHundredApplicationJSONAccountValuation() *GetAccountValuationAccountValuation {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONAccountValuation
}

func (o *GetAccountValuationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAccountValuationResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *GetAccountValuationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAccountValuationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
