// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/upvest-dev-sample-sdk/pkg/models/shared"
	"github.com/speakeasy-sdks/upvest-dev-sample-sdk/pkg/utils"
	"net/http"
	"time"
)

// ListMandatesOrder - Sort order of the result list if the `sort` parameter is specified. Use `ASC` for ascending or `DESC` for descending sort order.
type ListMandatesOrder string

const (
	ListMandatesOrderAsc  ListMandatesOrder = "ASC"
	ListMandatesOrderDesc ListMandatesOrder = "DESC"
)

func (e ListMandatesOrder) ToPointer() *ListMandatesOrder {
	return &e
}

func (e *ListMandatesOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ASC":
		fallthrough
	case "DESC":
		*e = ListMandatesOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListMandatesOrder: %v", v)
	}
}

// ListMandatesSort - Field of resource to sort by
type ListMandatesSort string

const (
	ListMandatesSortID        ListMandatesSort = "id"
	ListMandatesSortCreatedAt ListMandatesSort = "created_at"
)

func (e ListMandatesSort) ToPointer() *ListMandatesSort {
	return &e
}

func (e *ListMandatesSort) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "id":
		fallthrough
	case "created_at":
		*e = ListMandatesSort(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListMandatesSort: %v", v)
	}
}

type ListMandatesRequest struct {
	// Use the `limit` argument to specify the maximum number of items returned.
	Limit *int `default:"100" queryParam:"style=form,explode=true,name=limit"`
	// Use the `offset` argument to specify where in the list of results to start when returning items for a particular query.
	Offset *int `queryParam:"style=form,explode=true,name=offset"`
	// Sort order of the result list if the `sort` parameter is specified. Use `ASC` for ascending or `DESC` for descending sort order.
	Order *ListMandatesOrder `default:"ASC" queryParam:"style=form,explode=true,name=order"`
	// https://tools.ietf.org/id/draft-ietf-httpbis-message-signatures-01.html#name-the-signature-http-header
	Signature string `header:"style=simple,explode=false,name=signature"`
	// https://tools.ietf.org/id/draft-ietf-httpbis-message-signatures-01.html#name-the-signature-input-http-he
	SignatureInput string `header:"style=simple,explode=false,name=signature-input"`
	// Field of resource to sort by
	Sort *ListMandatesSort `default:"created_at" queryParam:"style=form,explode=true,name=sort"`
	// Upvest API version (Note: Do not include quotation marks)
	UpvestAPIVersion *shared.APIVersion `default:"1" header:"style=simple,explode=false,name=upvest-api-version"`
	// Tenant Client ID
	UpvestClientID string `header:"style=simple,explode=false,name=upvest-client-id"`
	UserID         string `pathParam:"style=simple,explode=false,name=user_id"`
}

func (l ListMandatesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListMandatesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListMandatesRequest) GetLimit() *int {
	if o == nil {
		return nil
	}
	return o.Limit
}

func (o *ListMandatesRequest) GetOffset() *int {
	if o == nil {
		return nil
	}
	return o.Offset
}

func (o *ListMandatesRequest) GetOrder() *ListMandatesOrder {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *ListMandatesRequest) GetSignature() string {
	if o == nil {
		return ""
	}
	return o.Signature
}

func (o *ListMandatesRequest) GetSignatureInput() string {
	if o == nil {
		return ""
	}
	return o.SignatureInput
}

func (o *ListMandatesRequest) GetSort() *ListMandatesSort {
	if o == nil {
		return nil
	}
	return o.Sort
}

func (o *ListMandatesRequest) GetUpvestAPIVersion() *shared.APIVersion {
	if o == nil {
		return nil
	}
	return o.UpvestAPIVersion
}

func (o *ListMandatesRequest) GetUpvestClientID() string {
	if o == nil {
		return ""
	}
	return o.UpvestClientID
}

func (o *ListMandatesRequest) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}

// ListMandatesMandatesListResponseDirectDebitMandateAddress - Address. Must not be a P.O. box or c/o address.
type ListMandatesMandatesListResponseDirectDebitMandateAddress struct {
	// First address line of the address.
	AddressLine1 string `json:"address_line1"`
	// Second address line of the address.
	AddressLine2 *string `json:"address_line2,omitempty"`
	City         string  `json:"city"`
	// Country code. [ISO 3166 alpha-2 Codes](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
	Country string `json:"country"`
	// Postal code (postcode, PIN or ZIP code)
	Postcode string `json:"postcode"`
	// State, province, county. [ISO 3166 alpha-2 Codes](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2).
	State *string `json:"state,omitempty"`
}

func (o *ListMandatesMandatesListResponseDirectDebitMandateAddress) GetAddressLine1() string {
	if o == nil {
		return ""
	}
	return o.AddressLine1
}

func (o *ListMandatesMandatesListResponseDirectDebitMandateAddress) GetAddressLine2() *string {
	if o == nil {
		return nil
	}
	return o.AddressLine2
}

func (o *ListMandatesMandatesListResponseDirectDebitMandateAddress) GetCity() string {
	if o == nil {
		return ""
	}
	return o.City
}

func (o *ListMandatesMandatesListResponseDirectDebitMandateAddress) GetCountry() string {
	if o == nil {
		return ""
	}
	return o.Country
}

func (o *ListMandatesMandatesListResponseDirectDebitMandateAddress) GetPostcode() string {
	if o == nil {
		return ""
	}
	return o.Postcode
}

func (o *ListMandatesMandatesListResponseDirectDebitMandateAddress) GetState() *string {
	if o == nil {
		return nil
	}
	return o.State
}

// ListMandatesMandatesListResponseDirectDebitMandateType - Type of mandate.
// * RECURRENT -
type ListMandatesMandatesListResponseDirectDebitMandateType string

const (
	ListMandatesMandatesListResponseDirectDebitMandateTypeRecurrent ListMandatesMandatesListResponseDirectDebitMandateType = "RECURRENT"
)

func (e ListMandatesMandatesListResponseDirectDebitMandateType) ToPointer() *ListMandatesMandatesListResponseDirectDebitMandateType {
	return &e
}

func (e *ListMandatesMandatesListResponseDirectDebitMandateType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "RECURRENT":
		*e = ListMandatesMandatesListResponseDirectDebitMandateType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListMandatesMandatesListResponseDirectDebitMandateType: %v", v)
	}
}

type ListMandatesMandatesListResponseDirectDebitMandate struct {
	// Business Identifier Code (also known as SWIFT-BIC, BIC, SWIFT ID or SWIFT code) [ISO 9362](https://en.wikipedia.org/wiki/ISO_9362).
	Bic string `json:"bic"`
	// Timestamp of when user validated the mandate
	ConfirmedAt time.Time `json:"confirmed_at"`
	// Date and time when the resource was created. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
	CreatedAt time.Time `json:"created_at"`
	// Address. Must not be a P.O. box or c/o address.
	CreditorAddress ListMandatesMandatesListResponseDirectDebitMandateAddress `json:"creditor_address"`
	// Banking identifier of the creditor.
	CreditorID string `json:"creditor_id"`
	// Name of the creditor on the mandate.
	CreditorName string `json:"creditor_name"`
	// International Bank Account Number [IBAN](https://en.wikipedia.org/wiki/International_Bank_Account_Number).
	Iban string `json:"iban"`
	// Direct Debit Mandate unique identifier.
	ID string `json:"id"`
	// Type of mandate.
	// * RECURRENT -
	Type *ListMandatesMandatesListResponseDirectDebitMandateType `default:"RECURRENT" json:"type"`
	// User unique identifier.
	UserID string `json:"user_id"`
}

func (l ListMandatesMandatesListResponseDirectDebitMandate) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListMandatesMandatesListResponseDirectDebitMandate) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ListMandatesMandatesListResponseDirectDebitMandate) GetBic() string {
	if o == nil {
		return ""
	}
	return o.Bic
}

func (o *ListMandatesMandatesListResponseDirectDebitMandate) GetConfirmedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.ConfirmedAt
}

func (o *ListMandatesMandatesListResponseDirectDebitMandate) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *ListMandatesMandatesListResponseDirectDebitMandate) GetCreditorAddress() ListMandatesMandatesListResponseDirectDebitMandateAddress {
	if o == nil {
		return ListMandatesMandatesListResponseDirectDebitMandateAddress{}
	}
	return o.CreditorAddress
}

func (o *ListMandatesMandatesListResponseDirectDebitMandate) GetCreditorID() string {
	if o == nil {
		return ""
	}
	return o.CreditorID
}

func (o *ListMandatesMandatesListResponseDirectDebitMandate) GetCreditorName() string {
	if o == nil {
		return ""
	}
	return o.CreditorName
}

func (o *ListMandatesMandatesListResponseDirectDebitMandate) GetIban() string {
	if o == nil {
		return ""
	}
	return o.Iban
}

func (o *ListMandatesMandatesListResponseDirectDebitMandate) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *ListMandatesMandatesListResponseDirectDebitMandate) GetType() *ListMandatesMandatesListResponseDirectDebitMandateType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *ListMandatesMandatesListResponseDirectDebitMandate) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}

// ListMandatesMandatesListResponseMetaOrder - The ordering of the response.
// * ASC - Ascending order
// * DESC - Descending order
type ListMandatesMandatesListResponseMetaOrder string

const (
	ListMandatesMandatesListResponseMetaOrderAsc  ListMandatesMandatesListResponseMetaOrder = "ASC"
	ListMandatesMandatesListResponseMetaOrderDesc ListMandatesMandatesListResponseMetaOrder = "DESC"
)

func (e ListMandatesMandatesListResponseMetaOrder) ToPointer() *ListMandatesMandatesListResponseMetaOrder {
	return &e
}

func (e *ListMandatesMandatesListResponseMetaOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ASC":
		fallthrough
	case "DESC":
		*e = ListMandatesMandatesListResponseMetaOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ListMandatesMandatesListResponseMetaOrder: %v", v)
	}
}

type ListMandatesMandatesListResponseMeta struct {
	// Count of the resources returned in the response.
	Count int64 `json:"count"`
	// Total limit of the response.
	Limit int64 `json:"limit"`
	// Amount of resource to offset in the response.
	Offset int64 `json:"offset"`
	// The ordering of the response.
	// * ASC - Ascending order
	// * DESC - Descending order
	Order *ListMandatesMandatesListResponseMetaOrder `json:"order,omitempty"`
	// The field that the list is sorted by.
	Sort *string `json:"sort,omitempty"`
	// Total count of all the resources.
	TotalCount int64 `json:"total_count"`
}

func (o *ListMandatesMandatesListResponseMeta) GetCount() int64 {
	if o == nil {
		return 0
	}
	return o.Count
}

func (o *ListMandatesMandatesListResponseMeta) GetLimit() int64 {
	if o == nil {
		return 0
	}
	return o.Limit
}

func (o *ListMandatesMandatesListResponseMeta) GetOffset() int64 {
	if o == nil {
		return 0
	}
	return o.Offset
}

func (o *ListMandatesMandatesListResponseMeta) GetOrder() *ListMandatesMandatesListResponseMetaOrder {
	if o == nil {
		return nil
	}
	return o.Order
}

func (o *ListMandatesMandatesListResponseMeta) GetSort() *string {
	if o == nil {
		return nil
	}
	return o.Sort
}

func (o *ListMandatesMandatesListResponseMeta) GetTotalCount() int64 {
	if o == nil {
		return 0
	}
	return o.TotalCount
}

// ListMandatesMandatesListResponse - Mandates list
type ListMandatesMandatesListResponse struct {
	Data []ListMandatesMandatesListResponseDirectDebitMandate `json:"data"`
	Meta ListMandatesMandatesListResponseMeta                 `json:"meta"`
}

func (o *ListMandatesMandatesListResponse) GetData() []ListMandatesMandatesListResponseDirectDebitMandate {
	if o == nil {
		return []ListMandatesMandatesListResponseDirectDebitMandate{}
	}
	return o.Data
}

func (o *ListMandatesMandatesListResponse) GetMeta() ListMandatesMandatesListResponseMeta {
	if o == nil {
		return ListMandatesMandatesListResponseMeta{}
	}
	return o.Meta
}

type ListMandatesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// Mandates list
	MandatesListResponse *ListMandatesMandatesListResponse
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ListMandatesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ListMandatesResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *ListMandatesResponse) GetMandatesListResponse() *ListMandatesMandatesListResponse {
	if o == nil {
		return nil
	}
	return o.MandatesListResponse
}

func (o *ListMandatesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ListMandatesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
