// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/speakeasy-sdks/upvest-dev-sample-sdk/pkg/models/shared"
	"github.com/speakeasy-sdks/upvest-dev-sample-sdk/pkg/utils"
	"net/http"
	"time"
)

type RetrieveDirectDebitRequest struct {
	DirectDebitID string `pathParam:"style=simple,explode=false,name=direct_debit_id"`
	// https://tools.ietf.org/id/draft-ietf-httpbis-message-signatures-01.html#name-the-signature-http-header
	Signature string `header:"style=simple,explode=false,name=signature"`
	// https://tools.ietf.org/id/draft-ietf-httpbis-message-signatures-01.html#name-the-signature-input-http-he
	SignatureInput string `header:"style=simple,explode=false,name=signature-input"`
	// Upvest API version (Note: Do not include quotation marks)
	UpvestAPIVersion *shared.APIVersion `default:"1" header:"style=simple,explode=false,name=upvest-api-version"`
	// Tenant Client ID
	UpvestClientID string `header:"style=simple,explode=false,name=upvest-client-id"`
}

func (r RetrieveDirectDebitRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RetrieveDirectDebitRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *RetrieveDirectDebitRequest) GetDirectDebitID() string {
	if o == nil {
		return ""
	}
	return o.DirectDebitID
}

func (o *RetrieveDirectDebitRequest) GetSignature() string {
	if o == nil {
		return ""
	}
	return o.Signature
}

func (o *RetrieveDirectDebitRequest) GetSignatureInput() string {
	if o == nil {
		return ""
	}
	return o.SignatureInput
}

func (o *RetrieveDirectDebitRequest) GetUpvestAPIVersion() *shared.APIVersion {
	if o == nil {
		return nil
	}
	return o.UpvestAPIVersion
}

func (o *RetrieveDirectDebitRequest) GetUpvestClientID() string {
	if o == nil {
		return ""
	}
	return o.UpvestClientID
}

// RetrieveDirectDebit200ApplicationJSONCurrency - Alphabetic three-letter [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code.
// * EUR - Euro
type RetrieveDirectDebit200ApplicationJSONCurrency string

const (
	RetrieveDirectDebit200ApplicationJSONCurrencyEur RetrieveDirectDebit200ApplicationJSONCurrency = "EUR"
)

func (e RetrieveDirectDebit200ApplicationJSONCurrency) ToPointer() *RetrieveDirectDebit200ApplicationJSONCurrency {
	return &e
}

func (e *RetrieveDirectDebit200ApplicationJSONCurrency) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "EUR":
		*e = RetrieveDirectDebit200ApplicationJSONCurrency(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RetrieveDirectDebit200ApplicationJSONCurrency: %v", v)
	}
}

// RetrieveDirectDebit200ApplicationJSONStatus - Status of the direct debit
// * NEW - Direct debit is created but not started processing.
// * PROCESSING - Direct debit is in processing.
// * CONFIRMED - Direct debit was successfully processed.
// * CANCELLED - Direct debit was cancelled.
type RetrieveDirectDebit200ApplicationJSONStatus string

const (
	RetrieveDirectDebit200ApplicationJSONStatusNew        RetrieveDirectDebit200ApplicationJSONStatus = "NEW"
	RetrieveDirectDebit200ApplicationJSONStatusProcessing RetrieveDirectDebit200ApplicationJSONStatus = "PROCESSING"
	RetrieveDirectDebit200ApplicationJSONStatusConfirmed  RetrieveDirectDebit200ApplicationJSONStatus = "CONFIRMED"
	RetrieveDirectDebit200ApplicationJSONStatusCancelled  RetrieveDirectDebit200ApplicationJSONStatus = "CANCELLED"
)

func (e RetrieveDirectDebit200ApplicationJSONStatus) ToPointer() *RetrieveDirectDebit200ApplicationJSONStatus {
	return &e
}

func (e *RetrieveDirectDebit200ApplicationJSONStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NEW":
		fallthrough
	case "PROCESSING":
		fallthrough
	case "CONFIRMED":
		fallthrough
	case "CANCELLED":
		*e = RetrieveDirectDebit200ApplicationJSONStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for RetrieveDirectDebit200ApplicationJSONStatus: %v", v)
	}
}

// RetrieveDirectDebit200ApplicationJSON - Direct debit payment
type RetrieveDirectDebit200ApplicationJSON struct {
	// Account group unique identifier.
	AccountGroupID string `json:"account_group_id"`
	CashAmount     string `json:"cash_amount"`
	// Date and time when the resource was created. [RFC 3339-5](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6), [ISO8601 UTC](https://www.iso.org/iso-8601-date-and-time-format.html)
	CreatedAt time.Time `json:"created_at"`
	// Alphabetic three-letter [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code.
	// * EUR - Euro
	Currency *RetrieveDirectDebit200ApplicationJSONCurrency `default:"EUR" json:"currency"`
	// Direct debit funding request unique identifier
	ID string `json:"id"`
	// Direct Debit Mandate unique identifier.
	MandateID string `json:"mandate_id"`
	// Payment reference the end user will see in their bank statement for the corresponding direct debit booking (“Verwendungszweck”)
	RemittanceInformation *string `json:"remittance_information,omitempty"`
	// Status of the direct debit
	// * NEW - Direct debit is created but not started processing.
	// * PROCESSING - Direct debit is in processing.
	// * CONFIRMED - Direct debit was successfully processed.
	// * CANCELLED - Direct debit was cancelled.
	Status *RetrieveDirectDebit200ApplicationJSONStatus `json:"status,omitempty"`
	// User unique identifier.
	UserID string `json:"user_id"`
}

func (r RetrieveDirectDebit200ApplicationJSON) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *RetrieveDirectDebit200ApplicationJSON) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *RetrieveDirectDebit200ApplicationJSON) GetAccountGroupID() string {
	if o == nil {
		return ""
	}
	return o.AccountGroupID
}

func (o *RetrieveDirectDebit200ApplicationJSON) GetCashAmount() string {
	if o == nil {
		return ""
	}
	return o.CashAmount
}

func (o *RetrieveDirectDebit200ApplicationJSON) GetCreatedAt() time.Time {
	if o == nil {
		return time.Time{}
	}
	return o.CreatedAt
}

func (o *RetrieveDirectDebit200ApplicationJSON) GetCurrency() *RetrieveDirectDebit200ApplicationJSONCurrency {
	if o == nil {
		return nil
	}
	return o.Currency
}

func (o *RetrieveDirectDebit200ApplicationJSON) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *RetrieveDirectDebit200ApplicationJSON) GetMandateID() string {
	if o == nil {
		return ""
	}
	return o.MandateID
}

func (o *RetrieveDirectDebit200ApplicationJSON) GetRemittanceInformation() *string {
	if o == nil {
		return nil
	}
	return o.RemittanceInformation
}

func (o *RetrieveDirectDebit200ApplicationJSON) GetStatus() *RetrieveDirectDebit200ApplicationJSONStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *RetrieveDirectDebit200ApplicationJSON) GetUserID() string {
	if o == nil {
		return ""
	}
	return o.UserID
}

type RetrieveDirectDebitResponse struct {
	// HTTP response content type for this operation
	ContentType string
	Headers     map[string][]string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Direct debit payment
	RetrieveDirectDebit200ApplicationJSONObject *RetrieveDirectDebit200ApplicationJSON
}

func (o *RetrieveDirectDebitResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *RetrieveDirectDebitResponse) GetHeaders() map[string][]string {
	if o == nil {
		return nil
	}
	return o.Headers
}

func (o *RetrieveDirectDebitResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *RetrieveDirectDebitResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *RetrieveDirectDebitResponse) GetRetrieveDirectDebit200ApplicationJSONObject() *RetrieveDirectDebit200ApplicationJSON {
	if o == nil {
		return nil
	}
	return o.RetrieveDirectDebit200ApplicationJSONObject
}
